### ISSUE TITLE
Feature policy integration

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/gamepad#119]
In #73, @marcoscaceres wrote:

> So what if we added a feature policy to prevent third parties from accessing game pads unless the top-level document explicitly says it's ok? That would mitigate some of the privacy concerns and limit some of the damage.

There was consensus that it would be helpful.

**Comment by marcoscaceres** [comment]
Data to help us with decision making: https://www.chromestatus.com/metrics/feature/timeline/popularity/3054

**Comment by mrmcpowned** [comment]
Just to clarify, would the scenario be something like a webpage that embeds an iframe whose source is an external webpage that uses the Gamepad API?

**Comment by marcoscaceres** [comment]
@mrmcpowned, yes, correct... in which case the following would be needed by hosting site:

```HTML
<iframe allow="gamepad" src="https://third-party.com"></iframe>
```

Or a HTTP header that says `https://third-party.com` is ok to use gamepad... I think it's something like: 

```http
Feature-Policy: gamepad https://third-party.com
```
