### ISSUE TITLE
What's a good place to start contributing to the Gamepad spec?

### ISSUE THREAD

**Issue by mrmcpowned** [w3c/gamepad#121]
I wasn't sure of where exactly to ask this, but it seemed to make sense as an issue since I've seen most discussions happen here, though I understand it's also not exactly an "issue".

I've been following the API and this repo for a while, but haven't had a chance to look into contributing due to focusing more on school. Since that's finishing soon, I wanted to see where I could help contribute, but not exactly sure what would be a good entry point.

**Comment by marcoscaceres** [comment]
Hi @mrmcpowned, sorry for the massive delay. The best way to contribute to help with reviewing incoming pull requests, reading the spec and seeing if it makes sense, etc. 

I'd just start by reading over the spec and seeing if there are typos, or other issues. Another thing we need is more web platform tests. http://github.com/web-platform-tests/wpt/
