### ISSUE TITLE
button[16] not documented in the list of buttons.

### ISSUE THREAD

**Issue by Grovkillen** [w3c/gamepad#130]
https://github.com/w3c/gamepad/blob/33e64a4b408268fcef12cd5f33c082d933287f0b/index.html#L664

I suggest we call all the "middle cluster" buttons menu buttons instead. They are never used as player inputs (jump, shoot, move etc.).

**Comment by luser** [comment]
Years ago when I was actively working on this stuff I tried to come up with some terminology and apparently I called those "control buttons":
https://github.com/luser/gamepad-data#controller-layout

**Comment by nondebug** [comment]
When possible, I think it's better for the Standard Gamepad to be less opinionated about how specific buttons will be used. Even if these buttons are typically used for menus, I can think of many examples where they aren't.

"menu cluster" and "control cluster" both seem reasonable, but I don't see any downside to keeping "center cluster".

It's unfortunate that the Standard Gamepad doesn't provide any way to add more buttons to the cluster to support devices like Switch Pro Controller. In Chrome the "capture" button just gets tacked on to the end of the `buttons` array.
