### ISSUE TITLE
TPAC planning and specification status report

### ISSUE THREAD

**Issue by LJWatson** [w3c/gamepad#137]
TPAC will be virtual this year. W3C is finalising the details but it is likely there will be events for the whole W3C community during the week of 26 to 31 October (as originally planned), with WG able to organise their own meetings in/around that week.

There are two things we need you to do:
1. Let @marcoscaceres  and I know before 17 July if you want meeting time to talk about your specification.
2. Post a specification status report before 30 September.

The specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

Your specification status report from 2019 is at #99

**Comment by marcoscaceres** [comment]
We might want to meet with WebXR folks and have a catch-up. 

We might also want to meet with some additional industry folks to talk about future stuff... @nondebug might ping some folks. 

So we will book two hours.

**Comment by marcoscaceres** [comment]
Hey folks... sent you a cal invite for us to meet for TPAC at the following [time](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2020&month=10&day=29&hour=22&min=0&sec=0&p1=152&p2=224&p3=136):
 
San Francisco (USA - California) | Thursday, 29 October 2020 at 3:00:00 pm | PDT

Please feel free to invite more folks through the calendar entry.

**Comment by mrmcpowned** [comment]
Are there any opening for folks interested in listening in to these kinds of meetings? I'm curious to see what gets discussed at these kinds of meetups, including what occurs in regards to the gamepad api as well.

**Comment by marcoscaceres** [comment]
@mrmcpowned sorry for the delay in replying. You are most welcome to join the discussion or just listen in. Can you email me at marcos@marcosc.com and I'll send you a cal invite?

**Comment by marcoscaceres** [comment]
## What progress has your spec made in the last 12 months?

We added SecureContext IDL extended attributes to the spec and have been moving towards enabling the API only via permissions policy #112.

A rewrite of the algorithms (into actual algorithms) is underway, but not expected to complete until next year.   

## Is anything blocking your spec from moving to CR?

The stuff above needs to land and ship... plus we need to decide if there is anything else that should go into the spec. 

## If yes, what is your plan to unblock it and do you need any help?
