### ISSUE TITLE
Define ongamepadconnected/ongamepaddisconnected attributes

### ISSUE THREAD

**Issue by saschanaz** [w3c/gamepad#141]
Generally events are paired with corresponding attributes, so we probably want to define them.

**Comment by marcoscaceres** [comment]
Good point. Seems odd not to have them.

**Comment by marcoscaceres** [comment]
During editor's meeting, we concluded to add these to the spec.

**Comment by marcoscaceres** [comment]
Seems this is supported already in browsers... https://developer.mozilla.org/en-US/docs/Web/API/Window/ongamepaddisconnected ... but just strangely. The event handler IDL attribute is not there, but appears that once defined it receives an event.
