### ISSUE TITLE
asynchronous getGamepads

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/gamepad#17]
Channeling some feedback I have gotten browser privacy enthusiasts here:

The GamePad API increases fingerprinting risk, if it always returns all devices attached to the browser. It would be highly desirable if the `getGamepads()` call would spawn a chrome dialog that requests the user to select which gamepad to return (or an empty array and no dialog, if none are present).

This would be nicer in code, if the call returned a Promise, with the given spec, a user agent would have to block on getGamepads, which doesn't sound ideal.

I know that the ship may have sailed on this one, but I wanted to make sure this is tracked.

**Comment by sgraham** [comment]
I feel a dialog is unnecessary (and undesirable) given that explicit user
action is required before any data is returned.

**Comment by annevk** [comment]
I think the specification could give advice that if a user dialog is desired by an implementation, the implementation could have that dialog before dispatching the event that indicates that `getCamepads()` starts returning something useful, no?
