### ISSUE TITLE
button presses can be missed

### ISSUE THREAD

**Issue by pyalot** [w3c/gamepad#2]
It is possible (and not too uncommon @ 60hz) to miss a button press. The underlying OS-APIs do provide accurate press/release events. It should be possible to install event handlers on a gamepad to capture these events.

**Comment by luser** [comment]
This would be fixed by https://github.com/w3c/gamepad/issues/4

**Comment by pyalot** [comment]
That's correct.

**Comment by nondebug** [comment]
Closing as duplicate of #4
