### ISSUE TITLE
404 for standard_gamepad.svg on https://www.w3.org/TR/gamepad/standard_gamepad.svg

### ISSUE THREAD

**Issue by cvan** [w3c/gamepad#20]
Embedded [here](https://www.w3.org/TR/gamepad/#remapping):

<img width="60%" src="https://cloud.githubusercontent.com/assets/203725/12776198/d9ef7336-ca08-11e5-9e4d-0b48fd519a72.png" alt="screenshot of missing SVG">

**Comment by luser** [comment]
I don't actually know how the spec gets transformed from the GitHub repo to the W3C page. @AFBarstow, @siusin?

**Comment by siusin** [comment]
Fixed now. Thanks for this.
