### ISSUE TITLE
Consider changing gamepad-mapping API to match SDL2's

### ISSUE THREAD

**Issue by cvan** [w3c/gamepad#24]
I understand it was likely wisest to reduce the surface area of the Gamepad API when it was initially spec'd and implemented. But, today, it's cumbersome that the Gamepad API doesn't resemble SDL2's API.

emscripten-ported Unity/Unreal games to the Web are using SDL2 for input, joysticks, gamepads - and .

https://github.com/kripken/emscripten/blob/5f09184/src/library_browser.js

**Comment by luser** [comment]
I think changing the API in incompatible ways is a non-starter at this point, since we have broad adoption by browsers (Gecko, Blink, Edge).

What did you have in mind here, specifically?

**Comment by cvan** [comment]
The handling of [controller](https://wiki.libsdl.org/CategoryGameController) [mappings](https://wiki.libsdl.org/SDL_GameControllerMapping) (see [this crowdsourced listing [by 9 contributors]](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)) and [haptics](https://wiki.libsdl.org/CategoryForceFeedback) is mostly what I thought we could borrow from SDL.

There are Firefox bugs on file for Gamepad [mappings](https://bugzilla.mozilla.org/show_bug.cgi?id=855364) and [rumble haptic feedback](https://bugzilla.mozilla.org/show_bug.cgi?id=680289), which have good discussions. There are also spec issues on file in this repo for both of these as well: #7 and #19.

With that being said, we can probably close this. Although it breaks compatibility and arguably complicates the API surface area, I feel it could be worth a proper investigation of SDL's Gamepad API methods and capabilities to see what the Web-based API can keep the same. I'm not completely well versed in (w)asm, but the last time I was poking around, I noticed there's a lot of logic thrown away when games are exported to JS using emscripten and using the SDL Gamepad API: https://github.com/kripken/emscripten/blob/07b87426/src/library_sdl.js

I don't know if/where there are metrics for Gamepad usage in Firefox, Chrome, Edge, and Opera. The only thing I was able to find were these two Gamepad metrics from the [Chrome Platform Status > JS Usage page](https://www.chromestatus.com/metrics/feature/popularity), both at <= 0.0001% usage:
- [`PrefixedGamepad`](https://www.chromestatus.com/metrics/feature/timeline/popularity/291)
- [`DocumentCreateEventGamepadEvent`](https://www.chromestatus.com/metrics/feature/timeline/popularity/1199)

I'm cool with closing this, if everyone's in agreement here. I can understand the rationale. Let me know your thoughts.

**Comment by cvan** [comment]
Also, on the emscripten/(w)asm point, I wonder if @juj has thoughts here.

**Comment by kearwood** [comment]
I have reviewed the SDL2 haptics API and incorporated some of its concepts into the WebIDL I have proposed with my comment to PR 32 (https://github.com/w3c/gamepad/pull/32).

I have arranged the interfaces so that simple pulse haptic feedback can be done in a single line, while enabling enough functionality that libraries could provide an SDL2 compatible haptic API.

**Comment by sagoston** [comment]
> I'm cool with closing this, if everyone's in agreement here. I can understand the rationale. Let me know your thoughts.

Closing this and we'll have individual issues for mapping/haptics for V2
