### ISSUE TITLE
The productID/name and vendorID/name should be separated

### ISSUE THREAD

**Issue by pyalot** [w3c/gamepad#3]
The current specification has the names/IDs of the product and vendor mangled together in a gamepad object member "id".

It would be proper to to separate these out (as the underlying OS drivers also do) and report it as objects like:
- gamepad.vendor.id
- gamepad.vendor.name
- gamepad.product.id
- gamepad.product.name

**Comment by luser** [comment]
Duping to https://github.com/w3c/gamepad/issues/12
