### ISSUE TITLE
Handedness of controllers

### ISSUE THREAD

**Issue by toji** [w3c/gamepad#30]
For VR controllers (and I'd imagine possibly some others?) it can be useful for developers to know which had the user is holding a controller in. I had planned to maybe bake this into the gamepad name ("Oculus Touch Left") but there's also device like the Vive wands that can switch which hand they're detected as dynamically. For that reason and developer convenience I'd like to propose a handedness enum:

```
enum GamepadHand {
    "", // Both hands or unknown
    "left",
    "right",
};

partial interface Gamepad {
    GamepadHand hand; // The hand the controller is held in
};
```

Most gamepads would use the empty string because handedness is not really meaningful for them (which also makes it an easy default.) Only controllers that have a concept of handedness would need to set this to `left` or `right` specifically.

**Comment by luser** [comment]
This seems straightforward and inoffensive.

**Comment by beidson** [comment]
I don't object to the content of the proposal.

I strongly object to doing it in the current working version of the spec. For a _long time_ there's been talk about getting the current spec cleaned up and moved to CR, and I still strongly support that.

I think this should wait until version 2.

**Comment by marcoscaceres** [comment]
This is covered by the XR spec:
https://immersive-web.github.io/webxr/#enumdef-xrhandedness
