### ISSUE TITLE
Snapshot API as "Version 1" CR

### ISSUE THREAD

**Issue by toji** [w3c/gamepad#31]
As brought up in #30, we should probably snapshot the API as it exists today to be cleaned up and submitted for ratification. Khronos has done this with the WebGL API in the past by simply branching the repo and maintaining that as the 1.0, 1.1, 1.2 etc snapshots going forward. When needed changes that are beneficial to all versions get merged back into those branches, but the overall structure of the APIs and conformance tests stay largely static.

Snapshotting the API will allow the master branch to continue evolving to include suggestions like #19, #25, and #30 without worrying about how they might impact near-term spec ratification.

**Comment by LJWatson** [comment]
This seems like a good thing to do.

The rough steps would be to publish an updated WD based on the current ED. With that we can post a CFC to the WG to progress the spec to CR.

Looking ahead to CR exit, we will need an implementation report that documents the implementations for each feature in the spc. Do we have tests for the features?

Pinging @siusin as team contact for Gamepad.

**Comment by luser** [comment]
We have a few tests, they're not comprehensive:
http://w3c-test.org/gamepad/

We still need a few things clarified in the spec to usefully progress it to CR, unfortunately I just have never found the time to do them: definitely https://github.com/w3c/gamepad/issues/8, and I would really like to have https://github.com/w3c/gamepad/issues/12 or something like it to deal with the vagueness of the current `id` attribute.

**Comment by luser** [comment]
The source for those tests:
https://github.com/w3c/web-platform-tests/tree/master/gamepad

**Comment by siusin** [comment]
+1
Happy to help with testing and the publications :)

**Comment by beidson** [comment]
+1

**Comment by marcoscaceres** [comment]
Closing as we are reworking the spec. We will aim to publish a CR sometime next year.
