### ISSUE TITLE
Consider using Bikeshed for spec formatting

### ISSUE THREAD

**Issue by cvan** [w3c/gamepad#33]
[Bikeshed](https://github.com/tabatkins/bikeshed) to make all this formatting easier/automatic.

**Comment by luser** [comment]
Someone asked about this previously. I have no great love for the stuff we're using, but I am also not going to do the work to convert the existing spec. If someone wants to convert to Bikeshed I'd be happy to merge that change.

**Comment by cvan** [comment]
If I have some spare cycles, I'd totally be down. And I could write a Webhook to make everything automated.

**Comment by marcoscaceres** [comment]
Not worth the effort.
