### ISSUE TITLE
Support gamepad speakers/headsets

### ISSUE THREAD

**Issue by HughIsaacs2** [w3c/gamepad#36]
Many gamepads have speakers now (PS4 DualShock 4, Wii U Gamepad, Wii remote, Steam Controller, etc...) and many have ports/headphone/headset jacks (PS4 DualShock 4, Xbox 360 Controller, Xbox One Controller, Wii U Gamepad).

I'm unsure if this is really needed but I feel the Audio Output Devices and getUserMedia APIs should have some sort of way to be tied to a specific gamepad via it's index.

Say for the Audio Output Devices API, the index of a gamepad with a speaker should be usable as a sinkId in some way.

Of course there needs to be a way to check to see if a gamepad has a headset jack, microphone or speaker in the first place.

**Comment by marcoscaceres** [comment]
These should show up as audio devices by the system, so we wouldn't expose these in the API.

**Comment by HughIsaacs2** [comment]
> These should show up as audio devices by the system, so we wouldn't expose these in the API.

The specific request wasn't an audio API directly, but something to tell a web app just which audio device pertains to which gamepad.

**Comment by marcoscaceres** [comment]
Ah, sorry, yes. You are right @HughIsaacs2. I think we are still going to consider this out of scope for now, but we may come back to it down the road.
