### ISSUE TITLE
Expose controller 3d mesh

### ISSUE THREAD

**Issue by caseyyee** [w3c/gamepad#41]
It would be nice to be able to have a 3D mesh associated with the gamepad object returned.   Especially useful for the WebVR case where you won't be able to see your controller through the headset.   This will also help with making sure that controllers are consistently represented through different experiences (when desired).

Steam VR offers models as part of their runtime for this same reason (stored in SteamApps/common/OpenVR/resources/rendermodels/)

**Comment by luser** [comment]
I think this is out of scope for this spec. This seems like something that a content library could easily handle. I don't think browsers would do a very good job of shipping an up-to-date set of models of controllers.

**Comment by caseyyee** [comment]
makes sense.  thanks!
