### ISSUE TITLE
Spec broken because of use of "old school" WebIDL mode

### ISSUE THREAD

**Issue by tidoust** [w3c/gamepad#47]
Not sure if that's a well-known issue, but since I could not find it in the list, I thought I'd raise one.

The Gamepad API appears to be still using the "old school" WebIDL mode that has been deprecated from ReSpec a few years ago. It is also broken: for some reason, ReSpec now swallows most of the attributes and methods descriptions, leaving only things such as "MUSTMUSTSHOULDSHOULD" in practice. Malicious minds might argue that this actually makes specs easier to understand... Anyway.

@marcoscaceres warned he would [remove support for old school WebIDL from ReSpec for xmas](https://lists.w3.org/Archives/Public/spec-prod/2016OctDec/0038.html) and offered to help with the migration.

**Comment by marcoscaceres** [comment]
Unless someone beats me to it: 
https://github.com/w3c/respec/wiki/WebIDL-Guide

**Comment by marcoscaceres** [comment]
Now fixed 🎉
