### ISSUE TITLE
 Orientation of the head

### ISSUE THREAD

**Issue by hoene** [w3c/gamepad#55]
In order to allow a realistic spatial audio rendering, the orientation of the head is of substantial importance. For example, VR glasses like Oculus Rift adapt 3D audio to current orientation of the head. Also, more and more headphones include a head tracker.

Albeit a headphone is no gamepad, here are already headtracking devices out here, which use the HID gamepad protocol.

Thus, I would suggest to enhance the  Enum GamepadHand by a value "head" - or even better, to rename GamepadHand to GamepadPlace...

**Comment by marcoscaceres** [comment]
out of scope. Or should be moved to WebXR?
