### ISSUE TITLE
Standard mapping image should be described in text

### ISSUE THREAD

**Issue by Crissov** [w3c/gamepad#57]
I see `standard_gamepad.svg` in the Github repository and at <https://w3c.github.io/gamepad/>, but it’s 404ing at <https://www.w3.org/TR/gamepad/>.

The contents of the image should be described in text, too.

**Comment by ylafon** [comment]
Fixed in /TR, added to the manifest, so it won't happen again. I let this open for editors to work on your last point (unless you want to close and open a new issue for it)

**Comment by sgraham** [comment]
(Retitled to indicate remaining work on this issue)

**Comment by sagoston** [comment]
@Crissov What is it that you're looking for from the text description?  Care to create a PR for what you had in mind?

**Comment by chaals** [comment]
It would help if the text described the physical layout as represented in the image. For readers with visual disabilities this is pretty important.

(Making the SVG itself somewhat accessible would be good, too.)

**Comment by sagoston** [comment]
Made an attempt to describe the physical layout.  Open to suggestions and improvements.

**Comment by marcoscaceres** [comment]
Closing as the SVG has been updated and we've provide text describing the mapping. However, let us know if it's still not suitable and I can reopen this.
