### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/gamepad#60]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by scheib** [comment]
I would like a discussion to solicit interest and feedback on Gamepad [vibration](https://github.com/w3c/gamepad/blob/gh-pages/FeatureRequests.md) and [extensions](https://w3c.github.io/gamepad/extensions.html). 10 minutes would be sufficient to gather high level comments from those present, but then I would expect 30 or 60 minutes outside of the WG meeting to work with any other party interested in how to progress the specification.

**Comment by LJWatson** [comment]
Thanks scheib. Let's call it 30 minutes (to allow for discussion during the meeting).
