### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/gamepad#69]
Issue to track wide review:
* A11y: request sent to [APA WG](https://lists.w3.org/Archives/Public/public-apa/2018May/0020.html)
* Architecture: request filed as w3ctag/design-reviews#281 No issues
* I18n: request filed as w3c/i18n-activity#569 No issues
* Privacy: request sent to [Privacy IG](https://lists.w3.org/Archives/Public/public-privacy/2018AprJun/0030.html) Issues filed: #74 #76 * Security: request sent to [Web Security WG](https://lists.w3.org/Archives/Public/public-web-security/2018May/0000.html) Issues filed: #73 #72 #71 #70

**Comment by LJWatson** [comment]
@Sagoston @sgraham 

@R12a has suggested we go through the [i18n checklist](https://www.w3.org/International/techniques/developing-specs
). Could one of you take a run at this?

Also, there are three open PR. Is there any reason those haven't been merged? When we start the journey to Candidate Recommendation (CR), we'll need to document the reasons for any open PR that remain.

Thanks.

**Comment by marcoscaceres** [comment]
Closing, as we have a better tool for this now at the W3C... 
https://www.w3.org/PM/horizontal/review.html?shortname=gamepad
