### ISSUE TITLE
Obsolete dependencies

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/gamepad#79]
The dependencies section seems to cite a bunch of obsoleted specs/things. 

 * DOMHighResTimeStamp
 * WindowAnimationTiming
 * PerformanceTiming

Also, [[!NAVIGATOR]] is probably not the most authoritative thing to cite. Please cite [[!HTML]] instead, as it's more maintained.

**Comment by sagoston** [comment]
Could you please submit a PR with these fixes?

**Comment by ylafon** [comment]
852704cf6bb3216cd1ef46d6d8ded28740c4e1be fixed it (merging PR #84)
