### ISSUE TITLE
Length of getGamepads() array

### ISSUE THREAD

**Issue by nondebug** [w3c/gamepad#82]
The spec describes the length of the array returned by getGamepads() in terms of the indices of Gamepad objects in the returned array. However, it doesn't describe the length when there are no objects in the array.

Should it specify an empty array when there are no connected gamepads?

Also, should the array shrink-to-fit when gamepads are disconnected?

**Comment by mrmcpowned** [comment]
As much as it would make sense to do away with `GamepadList` a scenario I see occurring would be in the case where we have 3 or 4 gamepads connected and any of the middle gamepads disconnect.

In that case, the natural logic is to rebuild the array so there are no holes in it in terms of items. Doing that would disrupt the ability to properly keep track of gamepads that are still connected by shifting the indices.

Instead, why not modify the length property to reflect the number of connected gamepads, or simply have a separate property that keeps track of that altogether?

**Comment by nondebug** [comment]
To clarify, I'm not proposing that we would change the indices of any connected gamepads, just shortening the array so the last element is non-null. We should preserve holes in the array for the reason you gave.

**Comment by mrmcpowned** [comment]
In that case, wouldn't shortening it still leave holes?

In the event where all 4 gamepads are connected, and the 4th is then disconnected, the proposed array would have 3 items and the 4th would be out of bounds.

I think we should think about the `GamepadList` not as a traditional list but as something akin to port assignments on a home console. To remove an unoccupied index would imply that those indices are unavailable for usage and, in my option, to create that kind of assumption would not be something useful to developers.

**Comment by nondebug** [comment]
In your scenario, the spec suggests that the length of the array should be 3:

> The length of the array returned MUST be one more than the maximum index value of the Gamepad objects returned in the array.

The disconnected gamepad (index 3) is not included in the array returned by getGamepads(), so the maximum index value is 2 and the array length is 3.

> In the event where all 4 gamepads are connected,

It's not clear to me why 4 gamepads is the limit. The spec doesn't define a limit and I think in general there's no reason why there should be a hard-coded limit. If an implementation supports an unlimited number of connected gamepads, what should the array returned from getGamepads() look like with no gamepads connected?

> I think we should think about the GamepadList not as a traditional list but as something akin to port assignments on a home console.

That sounds reasonable. Perhaps the array should grow and not shrink in order to preserve the indices of disconnected gamepads (in case they are reconnected).

**Comment by knyg** [comment]
@nondebug @mrmcpowned I agree with your comments.  Let me know if you have any comments/suggestions on the PR.

**Comment by nondebug** [comment]
Closing this since the "...MUST be one more than the maximum index value..." language is no longer in the spec.
