### ISSUE TITLE
Gamepad event timing

### ISSUE THREAD

**Issue by nondebug** [w3c/gamepad#83]
The spec describes gamepadconnected and gamepaddisconnected events but does not describe the timing of when these events should be dispatched or how they interact with the navigator.getGamepads polling method. I'd like to propose stricter guarantees on this timing.

To ensure there is no difference between accessing the gamepad state through event.gamepad or navigator.getGamepads() from an event listener:

> If a gamepad event is dispatched and there is an event listener for the event, the gamepad state returned by navigator.getGamepads() MUST match the gamepad state in event.gamepad. The gamepad state returned by navigator.getGamepads() MUST remain the same until all event listeners have completed.

(Possibly this should also specify that the Gamepad object is the same object as in the getGamepads array.)

To ensure a sane ordering of events so that event listeners can accurately track which gamepads are currently connected:

> gamepadconnected and gamepaddisconnected MUST NOT be dispatched twice in a row for the same gamepad. For instance, if a gamepad is determined to have been disconnected and connected in the same polling update then gamepaddisconnected MUST be dispatched first.

(Possibly also specify that gamepaddisconnected must not be dispatched before gamepadconnected for a particular gamepad, although this may already be implied by the spec.)

**Comment by nondebug** [comment]
I'm pursuing this in support of adding gamepad button and axis events, which should require stricter timing so that listeners receive button and axis events in a predictable order. These events should also be dispatched correctly with respect to connection events to ensure we don't dispatch button and axis events for a gamepad that hasn't dispatched gamepadconnected yet.

I've also run into issues with test APIs that are capable of changing gamepad state from inside an event listener. This may cause re-entry into the event handler (e.g., by changing a gamepad to disconnected while inside the gamepadconnected listener) which can lead to unexpected behavior. Perhaps the gamepad API should specify more broadly when gamepad state may or may not be changed in order to better support test APIs like this.

**Comment by marcoscaceres** [comment]
We should look at how the eventing is done in Gecko... we might meed to add an internal slot that represents the array of gamepads, and we manipulate that array through the connect and disconnect events. 

https://github.com/mozilla/gecko-dev/tree/master/dom/gamepad
