### ISSUE TITLE
Clarify what "up" and "down" mean for input axes

### ISSUE THREAD

**Issue by jacobcdewitt** [w3c/gamepad#94]
The spec says the following about the axes attribute for GamepadButton https://www.w3.org/TR/gamepad/#dom-gamepadbutton
"As appropriate, -1.0 SHOULD correspond to "up" or "left", and 1.0 SHOULD correspond to "down" or "right""

For a controller with a joystick that is perpendicular to the ground, does "up" mean the joystick is being pushed away from the user holding the controller and "down" mean the joystick is being pulled towards the user? In that case, the words "forwards" and "backwards" might be more accurate.

**Comment by marcoscaceres** [comment]
@jacobcdewitt seem like reasonable suggestions... PR? 🙏

**Comment by knyg** [comment]
@marcoscaceres @jacobcdewitt PR created.
