### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/gamepad#99]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by knyg** [comment]
- Work towards CR involved triaging issues valid for CR and v2 issues.  Additionally, the spec has been circulated to the wider audience to raise concerns about privacy and security.
- Need to gain consensus and close privacy/security issues to move forward.
- The plan is to get through all open issues with key members at TPAC and close the issues.
